### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ritviksahajpal** [ritviksahajpal/yield_forecasting#1]
- [ ] Attempt the steps outlined in MODIS NDVI (https://ritviksahajpal.github.io/yield_forecasting/installation.html#modis-ndvi) and insert images to illustrate how to do step 2 into the page. Please give your images meaningful names and store in the `images` folder.
- [ ] Attempt the steps outlined in AgERA5 and insert images to illustrate step 2. Please give your images meaningful names and store in the `images` folder.
- [ ] On clicking https://ritviksahajpal.github.io/yield_forecasting/geoprepare.html, the table of contents seems to loose some entries e.g. `GEOCIF`. Figure out why this is happening and fix it.
- [ ] Test how to add sample Python code here: https://ritviksahajpal.github.io/yield_forecasting/python.html
